require('dotenv').config()

const PORT = process.env.PORT

const DB_CONNECTSTRING = process.env.CONNECTSTRING

const SUPABASE_URL = process.env.SUPABASE_URL

const SUPABASE_SECRET_KEY = process.env.SUPABASE_SECRET_KEY

const TWILIO_ACCOUNT_SID = process.env.TWILIO_ACCOUNT_SID

const TWILIO_AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN

const TWILIO_PHONE_NUMBER = process.env.TWILIO_PHONE_NUMBER

module.exports = {
  PORT,
  DB_CONNECTSTRING,
  SUPABASE_URL,
  SUPABASE_SECRET_KEY,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER,
}
